const Colors = {
  black: '#000',
  white: '#fff',
  TextInputColor: '#2a2a2a',
  app_grey: '#BBBBBB',
  review_grey: '#BFBFBF',
  text_link: '#587FFF',
  green: "#2e8b57",
  dark_grey: '#707070',
  settings_seprator: '#BEBEBE',
  secondaryGray: '#F5F5F6',
  danger: '#FF0404',
  grayLight: '#a0a6ac',
  transparent: 'transparent',
  grayFed: '#F0F0F0',
  borderColor: '#F3F3F3',
  chatInputToolbarBorderColor: '#DCDCDC',
  chatInputBackgroundColor: '#F9F9F9',
  leftBubbleColor: '#DDE4EF',
  wishlistBackgroundColor: '#F8F8F8',
  wishlistBorderColor: '#EFEFEF',
  wishlistMoveToBagColor: '#EB971A',
  wishlistDiscountPriceColor: '#F89225',
  backgroundColor: '#FCFCFC',
  searchBorderColor: '#EFEFEF',
  greyFA: '#FAFAFA',
  productDetailSectionBorderColor: '#DDDBDF',
  primaryOrange: '#F89225',
  primaryYellow: '#FFE745'
}
export default Colors
