export const BASEURL = 'https://lifeofdesigner.keycorp.in'

export default {
    ROOT: 'https://lifeofdesigner.keycorp.in', // for Images n all
    REGISTER: BASEURL + '/api/v1/account/register',
    LOGIN: 'https://lifeofdesigner.keycorp.in/api/v1/account/login',
    OTP: BASEURL + '/api/v1/account/registration_otp/',
    OTP_PASS_CHANGE: BASEURL + '/api/v1/account/otp',
    CHANGE_PASSWORD: BASEURL + '/api/v1/account/change_password',
    CHANGE_PASSWORD_FROM_SIGNIN: BASEURL + '/api/v1/account/reset_password',
    GOOGLEAPI: BASEURL + '/api/v1/account/google/login/',
    APPLEAPI: BASEURL + '/api/v1/account/apple/login/',
    BANNER: BASEURL + '/api/v1/account/banner/',
    Product: BASEURL + '/api/v1/account/product/',
    deal: BASEURL + '/api/v1/account/deal/',
    profileGet: BASEURL + '/api/v1/account/get_profile/',
    profilePost: BASEURL + '/api/v1/account/edit_profile/',
    ProductListing: BASEURL + '/api/v1/account/product_list/',
    ProductListingEdit: BASEURL + '/api/v1/account/product_list/?id=',
    dealGet: BASEURL + '/api/v1/account/deal_list/',
    dealGetEdit: BASEURL + '/api/v1/account/deal_list/?id=',
    Put_Heart: BASEURL + '/api/v1/account/add_frvourite_products/',
    DEAL_FAVOURITE_ADD: BASEURL + '/api/v1/account/add_frvourite_deal/',

    REMOVE_FAVOURITE: BASEURL + '/api/v1/account/remove_frvourite_products/',
    REMOVE_FAVOURITE_DEAL: BASEURL + '/api/v1/account/remove_frvourite_deal/',

    GET_SEARCH: BASEURL + '/api/v1/account/products_search/?search=',
    GET_LIKE: BASEURL + '/api/v1/account/like/',
    GET_COMMENT: BASEURL + '/api/v1/account/comment_list/?product_id=',
    GET_DEAL_COMMENT: BASEURL + '/api/v1/account/deal_comment_list/?deal=',
    POST_LIKE: BASEURL + '/api/v1/account/like/',
    POST_COMMENT: BASEURL + '/api/v1/account/comment/',
    DEAL_LIKE: BASEURL + '/api/v1/account/like_deals/',
    DEAL_COMMENT: BASEURL + '/api/v1/account/comment_deals/',
    GET_SALE_PRODUCT: BASEURL + '/api/v1/account/product_list/?created_by',
    SET_WISHLIST: BASEURL + '/api/v1/account/products_favourite_list/',
    DEAL_SET_WISHLIST: BASEURL + '/api/v1/account/deal_favourite_list/',
    GET_SEARCH_DEAL: BASEURL + '/api/v1/account/deal_search/?search=',
    GET_PARTICULAR_PRODUCT_DATA: BASEURL + '/api/v1/account/one_product/',
    GET_PARTICULAR_DEAL_DATA: BASEURL + '/api/v1/account/one_deals/',
    GET_PARTICULAR_DEAL_DATA_UPDATED: BASEURL + '/api/v1/account/deal_details/?deal=',
    POST_REVIEW_RATING: BASEURL + '/api/v1/account/products_rating_review/',
    POST_REVIEW_RATING_FOR_DEAL: BASEURL + '/api/v1/account/deals_rating_review/',
    DEAL_REVIEW_RATING: BASEURL + '/api/v1/account/deals_rating_review/',
    POST_DELIVERY_ADDRESS: BASEURL + '/api/v1/account/delivery_address/',
    GET_DELIVERY_ADDRESS: BASEURL + '/api/v1/account/delivery_address/',
    CARD_DATA: BASEURL + '/api/v1/account/add-card-details/',
    POST_ADD_TO_CARD: BASEURL + '/api/v1/account/cart/',
    UPDATE_CART: BASEURL + '/api/v1/account/cart/',
    POST_BUY_NOW: BASEURL + '/api/v1/account/buy_now_products/',
    GET_SHOPPING_BAG: BASEURL + '/api/v1/account/current_cart_products/',
    PROFILE_DEACTIVATE: BASEURL + '/api/v1/account/delete_otp/',
    USER_DEACTIVATE: BASEURL + '/api/v1/account/delete_user/',
    FINAL_PROFILE_DEACTIVATE: BASEURL + '/api/v1/account/delete_user/',
    DEAL_BUY_NOW: BASEURL + '/api/v1/account/one_deals/',
    PAY_NOW: BASEURL + '/api/v1/payment/charge-through-card_id/',
    GET_NEW_ORDER: BASEURL + '/api/v1/payment/order_status_list/?order_status=new_order',
    GET_SHIPPED: BASEURL + '/api/v1/payment/order_status_list/?order_status=shipped',
    GET_DELIVERED: BASEURL + '/api/v1/payment/order_status_list/?order_status=delivered',
    GET_CONFIRMED: BASEURL + '/api/v1/payment/order_status_list/?order_status=confirmed',
    ORDERS: BASEURL + '/api/v1/payment/order_status_list/',
    ORDERS_SELLER: BASEURL + '/api/v1/payment/seller_order_status_list/',
    ORDER_CANCEL: BASEURL + '/api/v1/payment/order_rjected/',
    PUSH_NOTIFICATION: BASEURL + '/api/v1/account/push_notification/',
    ORDER_REJECT: BASEURL + '/api/v1/payment/order_rjected_list/',
    GET_NOTIFICATION: BASEURL + '/api/v1/account/current_user_notifaction/',
    GET_DATA_ON_ORDER_DELETE: BASEURL + '/api/v1/payment/order_status_list/?id=',
    CHAT_MESSAGE_SEND: BASEURL + '/api/v1/chat/message/send',
    REMOVE_USER_FROM_INBOX: BASEURL + '/api/v1/chat/delete_inbox/',
    GET_SEARCH_INBOX: BASEURL + '/api/v1/chat/search_inbox/',
    GET_SIZE_WHILE_UPLOAD: BASEURL + '/api/v1/account/product_size/',
    CANCEL_ORDER: BASEURL + '/api/v1/payment/order_product_remove/',
    RETURN_PRODUCT: BASEURL + '/api/v1/payment/product_return/',
    CONFIRM_ORDER: BASEURL + '/api/v1/payment/order_status_update/',
    PAYMENT_LIFE_OF_DESIGNER: BASEURL + "/api/v1/payment/order-invoice-v2/",
    // TRANSACTION_FOR_DEAL: BASEURL + "/api/v1/payment/orders-list?limit=10&offset={{offset}}&type=deal",
    TRANSACTION_FOR_DEAL: BASEURL + "/api/v1/payment/orders-list?type=deal",
    // TRANSACTION_FOR_PRODUCT: BASEURL + "/api/v1/payment/orders-list?limit=10&offset={{offset}}&type=cart"
    TRANSACTION_FOR_PRODUCT: BASEURL + "/api/v1/payment/orders-list?type=cart"






}